name: empty-commit
on: workflow_dispatch

jobs:
  empty-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v4
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
      - run: |
          git config user.signingkey 024CE4E863B28113A590C72349CFB1937571D066
      - uses: EndBug/add-and-commit@v9
        with:
          message: Update
          commit: --allow-empty -S
          committer_name: TonyPepeBear
          committer_email: tonybear55665566@gmail.com


