name: prettier

on:
  push:

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run Prettier
        run: |
          npm run prettier --check .
          
  prettier-commit:
    runs-on: ubuntu-latest
    needs:
      - prettier-check
    if: ${ jobs.prettier-check.status == "failure" }
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${ secrets.MY_GITHUB_TOKEN }

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Run Prettier
        run: |
          npm run prettier --write .

      - name: Commit and Push
        uses: EndBug/add-commit-message@v9
        with:
          add: "."
          message: "Prettier"
          committer_name: TonyPepeBear
          committer_email: tonybear55665566@gmail.com
